# DAY 3

Q1)Create a numpy array starting from 2 till 50 with a stepsize of 3.


In [4]:
import numpy as np
arr = np.arange(2,51,3)
print(arr)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47 50]


Q2)Accept two lists of 5 elements each from the user. Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it.

In [5]:
li1 = []
li2 = []

for i in range(5):
    n = int(input())
    li1.append(n)
    
for i in range(5):
    n = int(input())
    li2.append(n)
    
arr1 = np.array(li1)
arr2 = np.array(li2)
res = np.concatenate((arr1, arr2))
print(res)
final = np.sort(res)
print(final)

1
2
3
4
5
6
7
8
9
0
[1 2 3 4 5 6 7 8 9 0]
[0 1 2 3 4 5 6 7 8 9]


Q3)Write a code snippet to find the dimensions of a ndarray and its size

In [7]:
arr = np.arange(5)
print(arr)
print(arr.ndim)
print(arr.size)

[0 1 2 3 4]
1
5


Q4)How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet

In [8]:
arr_1d = ([1,2,3,4])
arr_2d = np.reshape(arr_1d, (2,2))
print(arr_2d)

[[1 2]
 [3 4]]


Q5)Consider two square numpy arrays. Stack them vertically and horizontally.

In [9]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])
ver = np.vstack((arr1,arr2))
hor = np.hstack((arr1,arr2))
print(ver)
print()
print(hor)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]

[[1 2 5 6]
 [3 4 7 8]]


Q6) How to get unique items and counts of unique items?

In [10]:
arr = np.array([1, 1, 2, 3, 4, 4, 1])

(unique, counts) = np.unique(arr, return_counts=True)
frequencies = np.asarray((unique, counts)).T

print(frequencies)

[[1 3]
 [2 1]
 [3 1]
 [4 2]]
